from .nodes import HAS_OFFICIAL_PREVIEW_API, NODE_CLASS_MAPPINGS as _LEGACY_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as _LEGACY_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

if HAS_OFFICIAL_PREVIEW_API:
    from .nodes import comfy_entrypoint

    __all__ = ["comfy_entrypoint", "NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
else:
    NODE_CLASS_MAPPINGS = _LEGACY_NODE_CLASS_MAPPINGS
    NODE_DISPLAY_NAME_MAPPINGS = _LEGACY_NODE_DISPLAY_NAME_MAPPINGS
    __all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
